from pathlib import Path
p=Path('src/components/AiAnalyst.tsx')
s=p.read_text(encoding='utf-8-sig')
s=s.replace('ChevronRight, CircleHelp,', 'ChevronRight, ChevronDown, CircleHelp,')
s=s.replace("import { providerNames, requestLiveAnalysis, requestResearch }", "import { requestResearch }")
s=s.replace("  stage: 'local' | 'local-complete' | 'searching-web' | 'web' | 'analyzing' | 'done' | 'error';", "  stage: 'local' | 'local-complete' | 'planning' | 'searching-web' | 'searching-more' | 'reading' | 'checking' | 'web' | 'analyzing' | 'done' | 'error';\n  entities?: string[];\n  reading?: { completed: number; total: number };")
s=s.replace("type LiveState = { status: 'idle' | 'loading' | 'success' | 'error'; question: string; analysis?: LiveAnalysis; error?: string };\n", '')
s=s.replace("  const [live, setLive] = useState<LiveState>({ status: 'idle', question: suggestedQuestions[0] });\n", '')
s=s.replace("  const liveReady = live.status === 'success' && live.question === submitted && Boolean(live.analysis);\n  const answer: Answer = liveReady ? { ...localAnswer, ...live.analysis } : localAnswer;", "  const useResearch = isCustom || research?.question === submitted;\n  const answer = localAnswer;")
s=s.replace("    setLive({ status: 'idle', question: submitted });\n", '')
a=s.index('  const runLive = ')
b=s.index('  const runResearch = ',a)
s=s[:a]+s[b:]
s=s.replace("    setLive({ status: 'idle', question });\n", '')
s=s.replace("local: event.results, total: event.total, stage: 'local-complete'", "local: event.results, entities: event.entities, total: event.total, stage: 'local-complete'")
s=s.replace("        if (event.stage === 'searching-web') return { ...previous, stage: 'searching-web' };", "        if (['planning', 'searching-web', 'searching-more', 'checking'].includes(event.stage)) return { ...previous, stage: event.stage as ResearchState['stage'] };\n        if (event.stage === 'reading') return { ...previous, stage: 'reading', reading: { completed: event.completed, total: event.total } };")
s=s.replace("if (event.stage === 'web') return { ...previous, web: event.results, stage: 'web' };", "if (event.stage === 'web') return { ...previous, web: event.results };")
s=s.replace("if (event.stage === 'analysis-error') return { ...previous, warnings: [...previous.warnings, event.error], stage: 'done' };", "if (event.stage === 'analysis-error') return { ...previous, error: event.error, stage: 'error' };")
s=s.replace("if (event.stage === 'done') return { ...previous, stage: 'done' };", "if (event.stage === 'done') return { ...previous, stage: previous.error ? 'error' : 'done' };")
s=s.replace('    const local = analyze(value, props);\n','')
a=s.index('    if (suggestedQuestions.some(item =>')
b=s.index('\n  };',a)
s=s[:a]+'''    if (props.aiConfigured || props.searchConfigured || !suggestedQuestions.some(item => item.toLowerCase() === value.toLowerCase())) runResearch(value);
    else { controller.current?.abort(); setResearch(null); }'''+s[b:]
s=s.replace("if (!isCustom) setShowSources(true)", "if (!useResearch) setShowSources(true)")
s=s.replace("isCustom ? 'analyst-research-sources'", "useResearch ? 'analyst-research-sources'")
s=s.replace("isCustom && research?.analysis ? [submitted, research.analysis.title, research.analysis.summary, ...research.analysis.findings.map(item => item.text), 'Caveat: ' + research.analysis.caveat].join('\\n')", """useResearch && research?.analysis ? reportText(submitted, research.analysis, [...research.local, ...research.web])""")
s=s.replace("  const providerName = props.aiProvider ? providerNames[props.aiProvider] : 'AI';\n", '')
s=s.replace("{isCustom ? <ResearchAnswer", "{useResearch ? <ResearchAnswer")
s=s.replace("onCitation={inspectSources} onCopy={copy}", "onAsk={ask} onCopy={copy}")
a=s.index("          {live.status === 'loading'")
b=s.index('          <section className="analyst-takeaway">',a)
s=s[:a]+s[b:]
a=s.index('          {liveReady &&')
b=s.index('          {isComparison',a)
s=s[:a]+s[b:]
s=s.replace('!liveReady && findings.length > 0', 'findings.length > 0').replace(': !liveReady && <p>', ': <p>')
s=s.replace("(isCustom ? ' analyst-evidence-snapshot'", "(useResearch ? ' analyst-evidence-snapshot'")
s=s.replace('{!isCustom &&', '{!useResearch &&').replace('{isCustom ? <ResearchSnapshot', '{useResearch ? <ResearchSnapshot')
a=s.index('function ResearchAnswer(')
b=s.index('\nfunction cityPicture',a)
new=Path('tmp-research-ui.txt').read_text(encoding='utf-8-sig')
s=s[:a]+new+s[b:]
s=s.replace("const namedCities = supportedCities.filter(city => question.toLowerCase().includes(city.city.toLowerCase()));", "const namedCities = supportedCities.filter(city => research?.entities?.includes(city.city) || question.toLowerCase().includes(city.city.toLowerCase()) || (city.city === 'Delhi NCR' && /\\\\b(delhi|ncr|gurgaon|gurugram|noida)\\\\b/i.test(question)));".replace('\\\\b','\\b'))
s=s.replace('Web results reviewed', 'Web sources found')
s=s.replace("  const webCount = research?.web.length || 0;", "  const webCount = research?.web.filter(item => item.status === 'read').length || 0;")
s=s.replace('Web sources found', 'Web pages read')
p.write_text(s,encoding='utf-8')
