import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const output = 'artifacts/opportunities';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1536, height: 1024 } });
const errors = [];
const chooseFilter = async (label, value) => {
  await page.getByRole('combobox', { name: label, exact: true }).click();
  const option = page.getByRole('option').filter({ has: page.locator('span') });
  const values = await option.evaluateAll(elements => elements.map(element => element.dataset.value));
  const index = values.indexOf(value);
  assert.ok(index >= 0, `Missing ${label} option: ${value}`);
  await option.nth(index).click();
};

page.on('pageerror', error => errors.push(error.message));
const url = (process.env.APP_URL || 'http://127.0.0.1:5173') + '/#ecosystem/opportunities';
const rows = page.locator('.opportunity-row');
const detail = page.getByRole('complementary', { name: 'Opportunity details' });
const resetFilters = async () => { const button = page.getByRole('button', { name: 'Reset filters' }); if (await button.count()) await button.click(); };
const waitForLogos = () => page.locator('.opportunity-logo img').evaluateAll(images => Promise.all(images.map(image => image.decode().catch(() => {}))));
try {
  await page.goto(url.replace('/opportunities', ''), { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Opportunities', exact: true }).click();
  assert.match(page.url(), /#ecosystem\/opportunities$/);
  await page.locator('.topbar > nav').getByRole('button', { name: 'Ecosystem', exact: true }).click();
  assert.match(page.url(), /#ecosystem\/opportunities$/);
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await rows.count(), 6);
  assert.equal(await page.getByRole('heading', { name: 'GCC opportunities in India' }).count(), 1);
  await waitForLogos();
  await page.screenshot({ path: `${output}/opportunities-desktop-final.png`, fullPage: true });
  await page.screenshot({ path: `${output}/opportunities-desktop-review.jpg`, type: 'jpeg', quality: 80 });
  const firstCompany = await page.locator('.opportunity-row-description > p > span').first().innerText();
  assert.equal(await detail.locator('.opportunity-detail-company h2').innerText(), firstCompany);
  const secondCompany = await rows.nth(1).locator('.opportunity-row-description > p > span').first().innerText();
  await rows.nth(1).click();
  assert.equal(await detail.locator('.opportunity-detail-company h2').innerText(), secondCompany);
  await page.getByRole('button', { name: 'Next opportunity page' }).click();
  assert.match(await page.locator('.opportunities-results-heading > p').innerText(), /Showing 7–12/);
  assert.equal(await detail.locator('.opportunity-detail-company h2').innerText(), await page.locator('.opportunity-row-description > p > span').first().innerText());
  await page.getByLabel('Search opportunities', { exact: true }).fill(`  ${firstCompany.toUpperCase()}  `);
  assert.equal(await rows.count(), 1);
  assert.equal(await detail.locator('.opportunity-detail-company h2').innerText(), firstCompany);
  await resetFilters();
  await chooseFilter('Function', 'Engineering');
  assert.ok(await rows.count() > 0);
  await chooseFilter('Team size', 'small');
  assert.ok(await rows.count() > 0);
  assert.ok((await rows.locator('.opportunity-row-meta p:first-child > span').allTextContents()).every(text => Number.parseInt(text) < 100));
  await page.getByRole('combobox', { name: 'Location preference', exact: true }).click();
  const cityOptions = await page.getByRole('option').locator('span').allTextContents();
  await page.keyboard.press('Escape');
  assert.ok(cityOptions.includes('Mumbai'));
  const currentCity = await rows.first().locator('.opportunity-row-location span').innerText();
  await chooseFilter('Location preference', currentCity.replace(' (Primary)', ''));
  const industry = await rows.first().locator('.opportunity-row-description > p > span').last().innerText();
  await chooseFilter('Industry', industry);
  assert.ok(await rows.count() > 0);
  await page.getByLabel('Search opportunities', { exact: true }).fill('no-matching-company-xyz');
  assert.equal(await rows.count(), 0);
  assert.equal(await detail.count(), 0, 'No stale detail for empty results');
  await resetFilters();
  await page.getByRole('tab', { name: 'Upcoming', exact: true }).click();
  if (await page.getByRole('button', { name: 'View all dates' }).count()) await page.getByRole('button', { name: 'View all dates' }).click();
  assert.ok(await rows.count() > 0);
  assert.equal(await detail.locator('.opportunity-status').innerText(), 'Upcoming');
  await page.getByRole('tab', { name: 'Closed', exact: true }).click();
  assert.equal(await rows.count(), 0);
  assert.equal(await page.getByRole('heading', { name: 'No closed opportunities recorded' }).count(), 1);
  await page.getByRole('tab', { name: 'Open opportunities' }).click();
  await resetFilters();
  await page.getByRole('button', { name: 'Close opportunity details' }).click();
  assert.equal(await detail.count(), 0);
  await rows.first().click();
  assert.equal(await detail.count(), 1);
  await detail.getByRole('button', { name: 'View company profile' }).click();
  let dialog = page.getByRole('dialog');
  assert.equal(await dialog.getByRole('heading', { name: firstCompany, exact: true }).count(), 1);
  assert.ok(await dialog.locator('a[href^="https://"]').count() > 0);
  await page.keyboard.press('Escape');
  await detail.getByRole('button', { name: 'Express interest', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Your name', { exact: true }).fill('Review User');
  await dialog.getByLabel('Organization', { exact: true }).fill('Example Partner');
  await dialog.getByLabel('Work email', { exact: true }).fill('review@example.com');
  await dialog.getByLabel('How you can help', { exact: true }).fill('Engineering support');
  await dialog.getByRole('button', { name: 'Save interest draft' }).click();
  assert.match(await dialog.getByRole('status').innerText(), /Interest draft saved/);
  assert.ok(await page.evaluate(() => Object.keys(JSON.parse(localStorage.getItem('gcc-compass-opportunity-interest-drafts') || '{}')).length) > 0);
  await page.screenshot({ path: `${output}/interest-draft.png` });
  await page.keyboard.press('Escape');
  const notification = page.getByRole('switch', { name: 'Opportunity notifications' });
  const oldValue = await notification.getAttribute('aria-checked');
  await notification.click();
  await page.reload({ waitUntil: 'networkidle' });
  assert.notEqual(await notification.getAttribute('aria-checked'), oldValue);
  const layoutResults = [];
  for (const [name, width, height] of [['laptop', 1280, 900], ['tablet', 1024, 900], ['mobile', 390, 844], ['small-mobile', 320, 740]]) {
    await page.setViewportSize({ width, height });
    await waitForLogos();
    await page.screenshot({ path: `${output}/opportunities-${name}-final.png`, fullPage: true });
    await page.screenshot({ path: `${output}/opportunities-${name}-review.jpg`, fullPage: true, type: 'jpeg', quality: 75 });
    const layout = await page.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth, outside: [...document.querySelectorAll('.opportunities-content button, .opportunities-content select')].filter(element => { const r = element.getBoundingClientRect(); return r.width > 0 && (r.left < 0 || r.right > innerWidth + 1); }).map(element => element.getAttribute('aria-label') || element.textContent) }));
    assert.equal(layout.width, layout.documentWidth, `${name} must not scroll horizontally`);
    assert.deepEqual(layout.outside, [], `${name} controls must stay inside viewport`);
    const textCollisions = await rows.evaluateAll(elements => elements.flatMap(row => {
      const textRect = element => { const range = document.createRange(); range.selectNodeContents(element); return range.getBoundingClientRect(); };
      const location = textRect(row.querySelector('.opportunity-row-location span'));
      const team = textRect(row.querySelector('.opportunity-row-meta p:first-child span'));
      return location.left < team.right && location.right > team.left && location.top < team.bottom && location.bottom > team.top ? [row.getAttribute('aria-label')] : [];
    }));
    assert.deepEqual(textCollisions, [], `${name} location and team labels must not overlap`);
    layoutResults.push({ name, ...layout });
  }
  await page.getByRole('button', { name: 'Explore partners', exact: true }).click();
  assert.equal(await page.locator('.ecosystem-partner-card').count(), 6);
  assert.match(page.url(), /#ecosystem$/);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'passed', firstCompany, checks: ['sidebar navigation and reload', 'live counts', 'selection updates', 'pagination selection', 'search', 'combined filters', 'no stale detail', 'upcoming and closed states', 'company profile', 'interest draft', 'notification preference persistence', 'responsive overflow', 'Explore partners regression'], layoutResults }, null, 2));
} finally { await browser.close(); }
